### ISSUE TITLE
migration problems - Lack of support for '~' expansion

### ISSUE THREAD

**Issue by danielporto** [fischerling/plugin-wd#10]
I'm migrating from zsh/wd to new fish/wd and facing problems.
first, there is a big deprecation warning to .warprc. I wish to use the same file
with both shells until I choose to settle in one. Is there a strong reason to
use another file if they have the same structure?

More importantly, although fish wd is able to list all directories, I cannot
warp into it:
cd: The directory '~/devel' does not exist  
it seems that the ~/ is not being expanded correctly.
I'm using a mac.

cd \~/devel works just fine
cd '\~/devel' fails.

\~/devel is a symlink to another path.

Thanks

**Comment by fischerling** [comment]
No there is no strong reason. Its just my personal preference to comply to the [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec and don't have all dotfiles in my home dir. That's why the deprecation message is only printed once per shell session.
If it really bothers you and you don't like symlinking `~/.warprc` to `~/.local/share/wd/warppoints` you could use `wd -q`.
