### ISSUE TITLE
wd not using ~/.warprc 

### ISSUE THREAD

**Issue by joepio** [fischerling/plugin-wd#11]
Hi, thanks for creating this!

I've been using wd for zsh for quite some time, and as a result, have a large `~/.warprc` file. 
When I installed `omf install wd`, and run it, I noticed that my old `warprc` isn't properly loaded.

When I run `wd warppoints-file`, I get `/home/joep/.local/share/wd/warppoints`, which differs from the readme.

When I try `wd -c ~/.warprc`, I get `set: Universal variable '__wd_warprc' is shadowed by the global variable of the same name.`

Do you know what's going on? Thanks in advance!

**Comment by fischerling** [comment]
Yea sorry the README is apparently not up-to-date.
This wd implementation searches for a warppoints file in those locations:

1. $WARP_FILE (environment variable)
2. $xdg_datda_dir/wd/warppoints (for xdg_data_dir in $XDG_DATA_DIRS)
2. $XDG_DATA_HOME/wd/warppoints
3. $HOME/.local/share/wd/warppoints
4. $HOME/.warprc (deprecated)

When it can't find a file at those locations it will silently create an empty warppoint file at 3. or 4.

So i think what happened is that wd created a new warppoint file under 3. and uses this empty one instead of your already populated $HOME/.warpc.

And the output `set: Universal variable '__wd_warprc' is shadowed by the global variable of the same name` you are seeing is from fish.

We remember the fish file location in the universal fish variable `__wd_warprc` so we don't have to search for it on each invocation.
Maybe overwriting it does not work the way I expected it to work. This seems like a bug and should be fixed.

**Comment by fischerling** [comment]
8d695d2d3aa7780f40f3136bc0a683619a6f6188 should fix the problem you encountered with the -c option.

The problem was that you probably had an global variable `__wd_warprc` from a previous invocation of wd in your fish session which shadows the newly created `__wd_warpc` universal variable. In a different fish session you should see your -c option having the desired effect.

To fix this issue for the current fish session we erase the variable `__wd_warprc` before giving it an universal scope.

**Comment by joepio** [comment]
Wow, thanks for the incredibly fast support! It works great now :)
